spring:
  profiles:
    active: local # 기본환경 설정

---
spring:
  profiles: local
  datasource:
    data: classpath:data-h2.sql # 시작할때 실행시킬 script
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true  #show query
    properties:     #콘솔 로그 줄바꿈 처리
      hibernate:
        format_sql: true
